### PR TITLE
Restore Forge Compatability

### PR DESCRIPTION
**Pull request by danorris709**
This PR restores Forge compatability.

The reasons it was not working previously:
- You had needlessly increased the minimum compatabiltiy for Mixin to JAVA_21. I say needlessly because you are not using any JAVA_21 language features in the mixins for NeoForge or Forge, and therefore making this change does nothing.
- You had not updated to the latest Gradle for Forge's MDK. This meant that you had reobf still enabled on the Forge compile, along with the refmaps, when Forge now uses runtime MojMaps. Therefore, the mixins would fail to apply and cause the game to crash.
- The mixin config was not specified in the JAR's manifest and therefore was not loading causing the game to crash upon right clicking in any inventory.

## Changes
I have removed the display test line, and the side check, in the Forge section and replaced it with the up to date `clientSideOnly=true` property in the mods.toml file.

Given the above that also allowed me to update the config screen registry, and thus remove the ClientHelper class.

## Screenshots
image

### CODE REVIEW

**Comment by YaLTeR** [comment]
> I have removed the display test line, and the side check, in the Forge section and replaced it with the up to date clientSideOnly=true property in the mods.toml file.

I believe it was originally added because it caused a red X in the server list: https://github.com/YaLTeR/MouseTweaks/issues/34

This new property works fine in terms of that, right? Also, what happens if you accidentally have it in the server mods folder?

**Comment by YaLTeR** [comment]
Thanks for the fixes! I'll try later today.

**Comment by danorris709** [comment]
> > I have removed the display test line, and the side check, in the Forge section and replaced it with the up to date clientSideOnly=true property in the mods.toml file.
> 
> I believe it was originally added because it caused a red X in the server list: #34
> 
> This new property works fine in terms of that, right? Also, what happens if you accidentally have it in the server mods folder?

I loaded a Forge server with the mod in the mods file and it was ignored! I'll check the server list for the red X now

**Comment by danorris709** [comment]
Yep I can confirm a server without the mod present, Forge server, does not have the red X with that line present!

**Comment by YaLTeR** [comment]
Perfect!

**Comment by YaLTeR** [comment]
Seems to work, thanks!

**Comment by YaLTeR** [comment]
Uploaded to CurseForge & modrinth.

**Pull request merged**
