### PR TITLE
Add GitHub Actions CI

### PR DESCRIPTION
**Pull request by Margen67**
Artifacts haven't been tested: ~~https://github.com/Margen67/MouseTweaks/actions/runs/1062126491~~
https://github.com/Margen67/MouseTweaks/actions/runs/1127057326

### CODE REVIEW

**Comment by YaLTeR** [comment]
Could you update to java 16? The 1.17.1 version and above will use that.

**Comment by YaLTeR** [comment]
I also see in the run that it made a MouseTweaks.zip with the 3 JARs, is it possible to make it upload 3 JARs separately? Because usually you only care about the regular JAR and having to go through the zip is annoying.

**Comment by Margen67** [comment]
> 
> 
> I also see in the run that it made a MouseTweaks.zip with the 3 JARs, is it possible to make it upload 3 JARs separately? Because usually you only care about the regular JAR and having to go through the zip is annoying.

You can't upload/download files directly: https://github.com/actions/upload-artifact/issues/39

**Comment by YaLTeR** [comment]
Thanks!

**Pull request merged**
