### PR TITLE
Fixes issue #2. Wheel movement was not getting reset when switching GUIs.

### PR DESCRIPTION
**Pull request by panoskj**
Fixes issue #2

### CODE REVIEW

**Comment by YaLTeR** [comment]
Wait, so what's going on here? I still haven't looked into that issue in depth.

This looks like it makes it so the very first update after switching GUIs has its wheel movement ignored (which shouldn't be necessary for the general case). How does this help?

**Comment by panoskj** [comment]
Here's what's going on: you open JEI's recipes GUI, do some scrolling, then close the recipes GUI. When it closes, the previous GUI opens again. In this case it was my inventory. Because recipes GUI doesn't call getDWheel, the next call to getDWheel is going to return the total wheel Movement since the recipes GUI opened. So when the previous GUI opens again, items may be moved unintentionally, if your mouse happens to be over them.

**Comment by YaLTeR** [comment]
So when JEI is open Mouse Tweaks' handler isn't being called? What about when no GUI is open at all, then MT's handler isn't called either and there doesn't seem to be any issues when a GUI gets opened.

I'm just checking if there's a potentially better solution since this feels a little like a workaround. I'll merge this if there's none.

**Comment by panoskj** [comment]
I guess Minecraft "consumes" mouse wheel events when there is no GUI, since you switch the held item with the wheel. I will let you know when have more information.

**Comment by YaLTeR** [comment]
Superseded by #20 I guess.

**Pull request closed without merging**
